### PR TITLE
Better server

### LINKED ISSUE #11: TODO: Add server
Add a simple server to run the website locally

### PR DESCRIPTION
**Pull request by theTisch21**
Closes #11 

## This pull request:
  

- Adds a server written in express-js
- Updates the README with instructions on how to run the server
- Add a .gitpod.yml file for [gitpod](https://gitpod.io)
- I've added the gitpod app to this repository for [prebuilds](https://www.gitpod.io/docs/prebuilds).

This is a work in progress. I'm still ironing out express, and will update this once #12 is merged.

### CODE REVIEW

**Comment by theTisch21** [comment]
Alright, it appears to be working well. Run the command `npm i` to install dependencies, then run `npm run start` in your terminal to start the website. It will then be accessible at `localhost:3000`. @Nathan-Yap, this is a pretty big refactor, please make sure all your changes merged correctly. The website files are now in the "views" folder, and they have .ejs extensions.

**Comment by theTisch21** [comment]
Hold on, this might break github pages. I'll fix that.

**Comment by theTisch21** [comment]
All the weird "dockerfile" and ".gitpod.yml" stuff is for a tool I sometimes use called "gitpod", which allows me to quickly spin up pre-configured environments for making quick changes. I often use it at school, when I just need to edit something quickly.

**Comment by theTisch21** [comment]
Alright, I've manually copied over the changes to an index.html. I'll find a better solution later

**Comment by theTisch21** [comment]
@Nathan-Yap Until I find a permanent fix for github pages, please edit both the index.html file in the root directory and the index.ejs file in the views directory to make changes to the webpage.

**Comment by theTisch21** [comment]
@Nathan-Yap Please disregard my previous comment. The main `index.html` is now in the "docs" folder. Please edit that to edit the website.

**Review by Nathan-Yap — APPROVED** [review]

**Pull request merged**
